name: GraphQL API Tests

# Event triggers
on:
  # Runs on pushes to main
  push:
    branches: [master]
  
  # Runs on PRs into main
  pull_request:
    branches: [master]
  
  # Can also be run manually
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'  
      
      - name: Verify npm and node versions
        run: |
          node --version
          npm --version
      
      - name: Install dependencies
        run: npm install
      
      - name: Check project structure
        run: |
          echo "Repository contents:"
          ls -la
          echo "Tests directory:"
          ls -la tests/ 2>/dev/null || echo "tests/ directory not found"
          echo "Jest config from package.json:"
          cat package.json | grep -A 10 '"jest"'
      
      - name: Run tests
        run: npm run test:ci

      - name: Run tests again
        run: npm test
